#!/bin/bash
# This hook is called by "git commit" after the commit message editor
# is closed. The default behavior is to run the tests and if they pass,
# the commit is allowed to proceed. If the tests fail, the commit is
# aborted. The hook can be bypassed by using the --no-verify option
# when running "git commit".

# Source common hook utilities
. "$(dirname "$0")/common.sh"

# Initialize branch name
init_branch_name

print_header "Checking \"$BRANCH_NAME\"..."

# Skip if on specific branches, or when amending or --no-verify flag is set
if should_skip_hook; then
  print_warning "Skipping post-commit hook... 🤨"
  exit 0
fi

# Check for existence of "new or modified" test files
NEW_TEST_FILES="$(git diff --diff-filter=ACDM --name-only --cached | grep -E '(./test/*)$')"
# Get all test files to run tests
CURRENT_TEST_FILES="$(git ls-files | grep -i -E '(_test\.rb)$')"

RAILS_TEST_EXIT_CODE=0
WORK_DONE=0

if [ -n "$NEW_TEST_FILES" ]; then
  #Count the number of new test files
  file_count=$(echo "$NEW_TEST_FILES" | wc -l)
  # Check if there are any new test files
  if [ "$file_count" -ne 0 ]; then
    print_warning "Found $file_count new test files in \"$BRANCH_NAME\"  🎉."
  fi

  for file in $NEW_TEST_FILES; do
    # if file is system test file run rake test:system filename
    if [[ "$file" == *"./test/system/*_test.rb" ]]; then
      print_warning "Running system test for \"$file\"..."
      bundle exec rake test:system "$file"
    else
      print_warning "Running unit test on \"$file\"..."
      bundle exec rake test "$file"
    fi
    # Capture the exit code from the test command to determine if it passed or failed
    if [ $? -ne 0 ]; then
      RAILS_TEST_EXIT_CODE=1
    fi
  done
  WORK_DONE=1
elif [ -n "$CURRENT_TEST_FILES" ]; then
  print_warning "No new tests found, running all Rails Tests ..."
  make test
  RAILS_TEST_EXIT_CODE=$?
  WORK_DONE=1
else
  print_error "No tests found in \"$BRANCH_NAME\". 🤨"
  RAILS_TEST_EXIT_CODE=1
fi

if [ ! "$RAILS_TEST_EXIT_CODE" -eq 0 ]; then
  git reset HEAD~
  print_error "Cannot commit, tests are failing. Use --no-verify to force commit. 😖"
  exit 1
fi

print_success "All tests are green, committing... 🎉"
exit 0
