# frozen_string_literal: true

require 'json'

# rubocop:disable Metrics/BlockLength, Layout/IndentHeredoc
namespace :ukhpi do
  desc 'Generate a client-side version of the aspects model'
  task aspects: %i[aspects_js move_aspects_js_file]

  # Translate the aspects model to JavaScript
  task aspects_js: :environment do
    puts 'Generating aspects.js ...'
    data_model = DataModel.new

    File.open('aspects.js', 'w') do |file|
      file << "// autogenerated by 'rake ukhpi:aspects'\n"
      file << <<EOL
modulejs.define( "aspects", [], function() {
  "use strict";
  return {
EOL

      sep = '  '
      data_model
        .measures
        .sort_by(&:local_name)
        .each do |measure|
          file << "#{sep}  #{measure.local_name}: {"
          file << "uri: \"#{measure.uri}\", "
          file << "label: \"#{measure.label}\", "
          file << "unitType: \"#{measure.unit_type}\""
          file << '}'
          sep = ",\n  "
        end

      file << <<EOL

  };
} );
EOL
    end
  end

  # Move the aspects.js file to the right location
  task move_aspects_js_file: :environment do
    puts 'Moving aspects.js ...'
    File.rename('aspects.js', 'app/assets/javascripts/aspects.js')
  end
end
