AllCops:
  Exclude:
    - app/models/regions-table.rb

# Customize rules
Metrics/LineLength:
  Max: 100

Metrics/ClassLength:
  Exclude:
    - test/**/*

Metrics/BlockLength:
  Exclude:
    - test/**/*
