AllCops:
  Exclude:
    - app/models/regions_table.rb
    - app/models/locations_table.rb

# Customize rules
Metrics/LineLength:
  Max: 100
  Exclude:
    - bin/**/*

Metrics/ClassLength:
  Exclude:
    - test/**/*

Metrics/BlockLength:
  Exclude:
    - test/**/*
    - lib/tasks/location.rake

Metrics/MethodLength:
  Exclude:
    - lib/tasks/location.rake
