require: rubocop-rails

AllCops:
  Exclude:
    - app/models/regions_table.rb
    - app/models/locations_table.rb
    - 'node_modules/**/*'

# Customize rules
Metrics/LineLength:
  Max: 100
  Exclude:
    - bin/**/*

Metrics/ClassLength:
  Exclude:
    - test/**/*

Metrics/BlockLength:
  Exclude:
    - test/**/*
    - lib/tasks/**/*

Metrics/MethodLength:
  Exclude:
    - lib/tasks/location.rake

Style/FormatStringToken:
  Enabled: false

Rails/OutputSafety:
  Exclude:
    - app/presenters/*.rb
