#!/bin/bash
# Run UKHPI tests

set -e

# bwm switched to using path because of permossion problem installing required gems
ssh-agent bash -c "ssh-add ~/.ssh/epi_deploy ; bundle --path vendor/bundle"
bundle exec rake test
