#!/bin/bash
# Run UKHPI tests

set -e

# Necessary to work-around 'cannot install such file -- bundler/dep_proxy' issue
gem install bundler

# bwm switched to using path because of permossion problem installing required gems
ssh-agent bash -c "ssh-add ~/.ssh/epi_deploy ; bundle --path vendor/bundle"
bundle exec rake test
