// JsFromRoutes CacheKey e3bff7c543f185d200e8cdda479c3992
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  edit: /* #__PURE__ */ definePathHelper('get', '/browse/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/browse'),
}
