// JsFromRoutes CacheKey 3e5136614e7c5d205f6018af78f84fb4
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  show: /* #__PURE__ */ definePathHelper('get', '/compare'),
}
