// JsFromRoutes CacheKey 55a694731267a506634cad0ef8bb13b4
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  new: /* #__PURE__ */ definePathHelper('get', '/download/new'),
}
