// JsFromRoutes CacheKey 73d01f55617a8812897ad2de5adc0cf8
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  show: /* #__PURE__ */ definePathHelper('get', '/print'),
}
